# -- Adapter指定 ---
adapter_type_name: "redmine_export.customizes.omds_exporter_adaptor.OmdsExporterAdaptor"  # OMDS用アダプターを指定

# -- Redmine設定 ---
redmine_settings:
  url: "https://om-digitalsolutions.tmxmine.com/"         # RedmineのURL
  api_key: "1cdd2e94fb80b60505ef49f7b248d86f88916559"     # RedmineのAPIキー

# --- パス設定 ---
# プロジェクトルートディレクトリからの相対パスで指定。Docker環境では /data 以下にマウントされます。
path_settings:
  input_path: "input"
  output_path: "output"